### ISSUE TITLE
Visual bug with damage indicators

### ISSUE THREAD

**Issue by razage** [Weissmoon/WeissAlbedo#1]
Whenever I hit a mob, the damage indicator is screwed up...not really sure how else to say that, so I'll include a screenshot. Disabling WeissAlbedo removes this issue, so here I am. I have tried both vanilla indicators and modded ones, and it's the same. 

I've circled the issue in red. It _should_ be a number indicating how much damage I hit the mob for.
![example](https://user-images.githubusercontent.com/9331220/33815428-e990eb18-ddf6-11e7-8bcf-95a95a94d1f6.png)

**Comment by razage** [comment]
False alarm. Need to keep getting to the root of this. Sorry!

**Comment by Weissmoon** [comment]
This is a know bug in Albedo. It's being looked into.
