### ISSUE TITLE
Custom Light Items does not appear to work

### ISSUE THREAD

**Issue by WolfieWaffle** [Weissmoon/WeissAlbedo#2]
I added "minecraft:stone" to both lists and when I held or dropped it nothing happened.

**Comment by WolfieWaffle** [comment]
UPDATE: It appears to render when you are in inventory mode, but not when looking around.

**Comment by Weissmoon** [comment]
How I coded those lists seems to need Minecraft to restart. I need to update the lists at runtime.

**Comment by Weissmoon** [comment]
This should be fixed in the new version (0.0.6)
