### ISSUE TITLE
Darkness fix regression

### ISSUE THREAD

**Issue by tyra314** [Weissmoon/WeissAlbedo#3]
Since the version 0.0.6a, the brightness level in-game is too bright, when the setting is on moody. It even feels like no difference, when you change the brightness slider.

*edit: An could you make this configurable, because I actually liked the dark nights.

**Comment by MCJediYoda** [comment]
I have the Cavern dimensions set to 0 for light level but the dimensions are like full brightness with 0.0.6a. I rolled back 0.0.4 and no issues.  The light level is as expected.

**Comment by Weissmoon** [comment]
Made World Light configurable in 0.0.7.

Currently this is a global option and does not support Hardcore Darkness blacklist.

**Comment by tyra314** [comment]
Thank you! Relevant XKCD: https://xkcd.com/1172/
