### ISSUE TITLE
[1.12.2-0.0.11] Entries not being applied after a restart

### ISSUE THREAD

**Issue by cybercat5555** [Weissmoon/WeissAlbedo#5]
(same person from Curseforge, but I though it would be better to bring it here instead of spam up there)

WeissAlbedo 1.12.2-0.0.11
Albedo 0.1.3
Forge 14.23.1.2602
Hardcore Darkness 1.12.2-2.0

When adding a custom entry using the in-game config editor, new entries work, but only for that session of the game. After the game is closed and re-opened later, new entries do not take effect and at least one new entry must be deleted, the new config saved, and then re-added in again and then saved again for all custom entries to work,. However though the entry itself is saved after the game is closed then re-opened later, but does not make the held/dropped item produce light unless the process mentioned above is done again.

Imgur album for better clarification: https://imgur.com/a/vu8fE

**Comment by Weissmoon** [comment]
This should be fixed in version 0.0.12.
